#!/usr/bin/env python3
"""Check (default) or write (--write) the structure every skill must follow.

Rules, per skills/<name>/:
  S1  SKILL.md frontmatter is valid strict YAML, `name` matches the directory,
      and `description` is a non-empty string of at most 1024 characters.
  S2  SKILL.md carries a generated "Contents" block right after its H1 title,
      listing its sections and its reference files.
  S3  Every markdown file under references/ longer than 100 lines carries the
      same kind of Contents block (or a hand-written "Contents" section near
      the top), so a partial read still shows the file's scope.
  W1  (warning only) SKILL.md bodies over 500 lines should move detail into
      reference files.

The Contents block is generated: edit headings, then run with --write.
Usage: python tests/skill_structure.py [--write] [skills-dir]
Exit 0 when every rule holds (warnings don't fail), 1 otherwise.
"""
import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

BEGIN = "<!-- contents: generated by tests/skill_structure.py --write; edit headings, not this block -->"
END = "<!-- /contents -->"
LONG_FILE = 100
MAX_ENTRIES_WITH_H3 = 25
MAX_DESCRIPTION = 1024
SKILL_BODY_WARN = 500
SKIP_DIRS = {"node_modules", "__pycache__", "evals", "test", "tests", "fixtures"}


def read(path):
    with open(path, "rb") as f:
        raw = f.read()
    crlf = b"\r\n" in raw
    return raw.decode("utf-8").replace("\r\n", "\n"), crlf


def write(path, text, crlf):
    if crlf:
        text = text.replace("\n", "\r\n")
    with open(path, "wb") as f:
        f.write(text.encode("utf-8"))


def split_frontmatter(text):
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None, "", text
    return m.group(1), text[: m.end()], text[m.end():]


def strip_block(body):
    """Remove an existing generated block (and the blank line after it)."""
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n\n?", re.S)
    return pattern.sub("", body, count=1)


def headings(body):
    """(level, text) for H2/H3 outside fenced code blocks."""
    out, fence = [], None
    for line in body.split("\n"):
        stripped = line.lstrip()
        m = re.match(r"(`{3,}|~{3,})", stripped)
        if m:
            marker = m.group(1)
            if fence is None:
                fence = marker[0] * len(marker)
            elif stripped.startswith(fence) and stripped.strip() == stripped.strip()[0] * len(stripped.strip()):
                fence = None
            continue
        if fence:
            continue
        h = re.match(r"(#{2,3})\s+(.*?)\s*#*\s*$", line)
        if h:
            out.append((len(h.group(1)), h.group(2)))
    return out


def slug(text, seen):
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)  # links -> their text
    s = s.replace("`", "").lower()
    s = re.sub(r"[^\w\- ]", "", s, flags=re.U).replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else f"{s}-{n}"


def h1_title(text):
    _, _, body = split_frontmatter(text)
    m = re.search(r"^#\s+(.+?)\s*$", body, re.M)
    return m.group(1) if m else None


def reference_files(skill_dir):
    """Markdown under references/ — the files a skill loads on demand.

    Other folders (assets/ templates copied into projects, agents/ briefs) are left alone.
    """
    found = []
    ref_root = os.path.join(skill_dir, "references")
    for root, dirs, files in os.walk(ref_root):
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
        for name in sorted(files):
            path = os.path.join(root, name)
            rel = os.path.relpath(path, skill_dir).replace(os.sep, "/")
            if name.endswith(".md") and rel != "SKILL.md":
                found.append(rel)
    return found


def has_manual_contents(body):
    """A hand-written Contents section near the top already does the job."""
    top = "\n".join(strip_block(body).split("\n")[:60])
    return re.search(r"^#{2,3}\s+(Table of )?Contents\s*$", top, re.M | re.I) is not None


def build_block(body, refs=None):
    # Anchors follow GitHub's rules, counting the block's own "Contents" heading first.
    seen = {"contents": 1}
    entries = [(level, text, slug(text, seen)) for level, text in headings(body)]
    if len(entries) > MAX_ENTRIES_WITH_H3:
        entries = [e for e in entries if e[0] == 2]
    lines = [BEGIN, "## Contents", ""]
    for level, text, anchor in entries:
        indent = "  " if level == 3 else ""
        lines.append(f"{indent}- [{text}](#{anchor})")
    if refs:
        lines += ["", "Reference files (open one when a step points to it):"]
        for rel, title in refs:
            lines.append(f"- `{rel}`" + (f": {title}" if title else ""))
    lines.append(END)
    return "\n".join(lines) + "\n\n"


def with_block(text, refs=None):
    """Return text with a fresh Contents block after the H1 (or frontmatter)."""
    _, fm, body = split_frontmatter(text)
    body = strip_block(body)
    block = build_block(body, refs)
    m = re.search(r"^#\s+.+\n", body, re.M)
    if m:
        rest = body[m.end():].lstrip("\n")
        return fm + body[: m.end()] + "\n" + block + rest
    return fm + "\n" + block + body.lstrip("\n")


def body_line_count(text):
    _, _, body = split_frontmatter(text)
    return strip_block(body).count("\n")


def check_frontmatter(skill, text):
    errors = []
    fm, _, _ = split_frontmatter(text)
    if fm is None:
        return [f"{skill}: SKILL.md has no frontmatter"]
    try:
        data = yaml.safe_load(fm) or {}
    except yaml.YAMLError as e:
        first = str(e).splitlines()[0]
        return [f"{skill}: frontmatter is not valid YAML ({first}); quote the description or use `description: >-`"]
    if data.get("name") != skill:
        errors.append(f"{skill}: frontmatter name {data.get('name')!r} != directory name")
    desc = data.get("description")
    if not isinstance(desc, str) or not desc.strip():
        errors.append(f"{skill}: description missing or not a string")
    elif len(desc) > MAX_DESCRIPTION:
        errors.append(f"{skill}: description is {len(desc)} chars (max {MAX_DESCRIPTION})")
    return errors


def main(argv):
    write_mode = "--write" in argv
    args = [a for a in argv if not a.startswith("--")]
    skills_dir = args[0] if args else os.path.join(os.path.dirname(__file__), "..", "skills")
    errors, warnings, changed = [], [], []

    for skill in sorted(os.listdir(skills_dir)):
        skill_dir = os.path.join(skills_dir, skill)
        skill_md = os.path.join(skill_dir, "SKILL.md")
        if not os.path.isfile(skill_md):
            continue
        text, crlf = read(skill_md)
        errors += check_frontmatter(skill, text)

        refs = []
        for rel in reference_files(skill_dir):
            path = os.path.join(skill_dir, rel)
            rtext, rcrlf = read(path)
            refs.append((rel, h1_title(rtext)))
            if body_line_count(rtext) > LONG_FILE and not has_manual_contents(split_frontmatter(rtext)[2]):
                expected = with_block(rtext)
                if expected != rtext:
                    if write_mode:
                        write(path, expected, rcrlf)
                        changed.append(f"{skill}/{rel}")
                    else:
                        errors.append(f"{skill}/{rel}: Contents block missing or stale (run --write)")

        expected = with_block(text, refs)
        if expected != text:
            if write_mode:
                write(skill_md, expected, crlf)
                changed.append(f"{skill}/SKILL.md")
            else:
                errors.append(f"{skill}/SKILL.md: Contents block missing or stale (run --write)")
        n = body_line_count(text)
        if n > SKILL_BODY_WARN:
            warnings.append(f"{skill}/SKILL.md: body is {n} lines (> {SKILL_BODY_WARN}); move detail to references/")

    for c in changed:
        print(f"WROTE {c}")
    for w in warnings:
        print(f"WARN  {w}")
    for e in errors:
        print(f"FAIL  {e}")
    print(f"{len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
